broker_id = "9999"
user_id = "123456"
password = "password"
market_front = "180.168.146.187:10131"
trade_front = "180.168.146.187:10130"
data_folder = "./test/fixtures"
instruments = ["cu2311", "cu2312"]